Changes to HDUL structure between scripts (Issue#129)
deepspace-ucsb/sdi_pipeline pull request #131
Opened 2021-10-14 23:25 UTC by JasperWebb

Changes to `Align`, `Subtract`, `Combine`, and `Extract`. Each script now appends changes to the HDUL instead of overwriting/rewriting HDU's or the full HDUL. 
Raw files I've tested start at 7MB after read align subtract extract write the files are 16.5MB
I've commented on most of the changes made here: https://github.com/ucsbdeepspace/sdi_pipeline/commit/efd28c8231ff8fe723b6df362ed18a3f2f9d2a67

- **HDUL structure after read align subtract extract write of norm_sources_merge branch currently:** 

![image](https://user-images.githubusercontent.com/10064835/137406995-ec16113a-676b-49db-baae-b9f07a6e5988.png)

- **HDUL structure after read align subtract extract write of nsm_hdul:** 
![image](https://user-images.githubusercontent.com/10064835/137408156-9ba138f5-0f38-4bc7-a29b-f341faafc4cf.png)

2021-10-17 23:48 UTC, PK0207 requested changes

2021-10-17 23:48 UTC, PK0207 commented on sdi/align.py
> +    #sources = [hdul[name] for hdul in hduls_list] ###Minor typo should be [hdu[name] for hdul in hduls_list]
Yes, do change this

2021-10-17 23:48 UTC, PK0207 commented on sdi/combine.py
> +def combine(hduls, name="ALGN"):
so we are creating a combine command so that we can save the align command?

2021-10-17 23:48 UTC, PK0207 commented on sdi/extract.py
> +@click.option("-r", "--read_ext", default="SUB", ## This should be changed to "SUB"
Yes it should

2021-10-18 00:30 UTC, JasperWebb commented on sdi/combine.py
> +def combine(hduls, name="ALGN"):
I'm not sure what you're asking here. By changing "SCI" to "ALGN" it points `combine` towards the "ALGN" hdu which contains the new, aligned, data instead of the SCI header which is no longer where we store the aligned data. 
Please correct me if I'm wrong but I don't think we use the non aligned data for anything else after this.
I'm looking into replacing SCI with ALGN after align.py to remove some of this confusion.

2021-10-18 18:30 UTC, PK0207 commented on sdi/combine.py
> +def combine(hduls, name="ALGN"):
We use SCI's headers, but I can't think of anything else. Even if we are overwriting the SCI images, the originals are preserved in a different directory so I don't see the issue. Thank you for clarifying.

2021-10-19 06:03 UTC, merged