Added new click command 'collate' which will take a list of HDULs con…
deepspace-ucsb/sdi_pipeline pull request #94
Opened 2021-05-20 02:24 UTC by kyyip

…taining a BinTableHDU of sources, preferably extracted using 'extract', and running the clustering methods DBSCAN or OPTICS to cluster sources to predict sky objects. These objects are returned as an appended TableHDU for each HDUL where the nth index of each table will refer to the same object, and the value of the index refers to the index of the source in the catalog HDU. Also added in the collate.py script is a function 'hdultocluster', which is not click integrated but will take a list of collated HDULs as an argument and return clusters/predicted objects as a list of ndarrays where each ndarray contains the sources corresponding to one particular sky object as well as source data based on the source catalog HDU used when collating.

2021-08-13 10:07 UTC, PK0207 reviewed
Weren't there more functions? I don't know if they are in this file specifically. But things like search I remember using and I don't see them here.
Other than that I believe everything here looks good. Things I was looking out for:

- What files are read in and how (glad that there are options for both xy and radec)
- How files are written out (making sure nothing from before is overwritten)
- How data is then accessed (hdultocluster is a very nice function to have, just makes things convenient)

2021-08-13 17:30 UTC, kyyip commented
You're right PK, there are more functions that were added to collate in my directory, but they weren't committed to git yet.  This pull request is 3 months old, but it contains the bare essentials to use collate.  I could recommit to add the extra functions if they're helpful, but it might make the script really long and really messy to look at.

2021-08-13 17:34 UTC, PK0207 commented
> You're right PK, there are more functions that were added to collate in my directory, but they weren't committed to git yet. This pull request is 3 months old, but it contains the bare essentials to use collate. I could recommit to add the extra functions if they're helpful, but it might make the script really long and really messy to look at.

I definitely used them when I used collate, so I do think they are helpful, but yeah get this pull request done I'd say before doing anything else. Another question I forgot to ask is when I asked you to run collate for me, you had run it multiple times to get the best result. Is that still necessary to do or will running the function once cover it?

2021-08-13 17:50 UTC, kyyip commented
You will need to run it multiple times and check each result if you want to optimize unfortunately.  I think it would be easy to write a function that runs collate multiple times using different parameter values and then keeps the best result, i.e. the result with the most clustered sources.

2021-09-14 02:27 UTC, varun-magesh requested changes
All in all, this is really really excellent code. It's well thought it, very clean, consistent in style with other pipeline functions, and takes something really really complicated and makes it look easy. Nice work Kelvin!

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +@click.option("-a", "--algorithm", default="DBSCAN", help="clustering algorithm of choice")
provide a list of allowable options here

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +@click.option("-c", "--coords", default="radec", help="coordinate system used to calculate distance between sources for clustering")
I like this

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +@click.option("-c", "--coords", default="radec", help="coordinate system used to calculate distance between sources for clustering")
but also include allowed options here

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +            print('Invalid value for coords, please use "radec" or "xy"')
restrict allowed options in the cmd arguments as well

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +        print('Invalid clustering method, please use "DBSCAN" or "OPTICS"')
ditto, add guards in the cmd as well

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +    for i in range(len(hduls)):
I think enumerate is preferred here over range(len(

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +            irdf[0] = irdf[0] + list(data["ra"])
why choose lists here as opposed to numpy manipulations? Both work, if this is what you intended then def keep it

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +    if len(collisions) > 0:
can finding and dealing with collisions be split into a helper function for clarity?

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +    count = len(hduls[0][tablename].data)
add a little description here of this function if possible, its utility is not clear from name

2021-09-14 02:27 UTC, varun-magesh commented on sdi/collate.py
> +        table = [fits.Column(name='objects'.format(j), format="I", array=np.array(cols), ascii=True)]
the j isn't actually put into this string... what's the format for

2021-09-14 02:29 UTC, varun-magesh commented
@kyyip  could you also write unit tests for this using the new framework if you have time? I won't hold up the merge for the unit tests, but I think it would be a helpful addition here, especially if you have the bandwidth to spare. Great work on this PR!

2021-09-17 19:54 UTC, kyyip commented on sdi/collate.py
> +            irdf[0] = irdf[0] + list(data["ra"])
I used lists, in order for _norm() to work.  Otherwise, I would have to find a different method to normalize them(irdfs) as numpy arrays.

2021-09-17 19:55 UTC, kyyip commented on sdi/collate.py
> +        table = [fits.Column(name='objects'.format(j), format="I", array=np.array(cols), ascii=True)]
I think this is a mistake I left from some previous code.  Thanks for pointing that out.

2021-09-17 23:17 UTC, kyyip commented on sdi/collate.py
> +    count = len(hduls[0][tablename].data)
This function really is used only once, and it's when collisions are being resolved,  mainly to get the coordinates of each cluster's sources before calculating the mean coordinate.  I'm going to remove this function and move the code into the collision section of the main function.

2021-10-09 22:35 UTC, kyyip commented on sdi/collate.py
> +            print('Invalid value for coords, please use "radec" or "xy"')
Restricted click command options to only 'radec' and 'xy'!

2021-10-09 22:35 UTC, kyyip commented on sdi/collate.py
> +        print('Invalid clustering method, please use "DBSCAN" or "OPTICS"')
Restricted click command options to only 'DBSCAN' and 'OPTICS'!

2021-10-09 22:36 UTC, kyyip commented on sdi/collate.py
> +    for i in range(len(hduls)):
Done!

2021-11-30 01:15 UTC, merged